### ISSUE TITLE
How to get x, y position and width, height of recognised text block in screen ?

### ISSUE THREAD

**Issue by AndriiRokobit** [MyScript/interactive-ink-additional-examples-android#2]
`val transform = editor.renderer.viewTransform
                        val left = transform.apply(box.x + 0, box.y)
                        val right = transform.apply(box.x + box.width - 0, box.y)

                        val x = left.x
                        val y = left.y`

I had try this, but that wrong

**Comment by myscript-developer** [comment]
Dear Andrii,

thank you for contacting us.

For a faster and more accurate answer, we recommend you submit any question you may have on our developer forum: https://developer-support.myscript.com/support/discussions.

In your case, I am not sure to understand what you are doing: are you in the "Text Document" part, and want to get the coordinates of the box? In that latter case, you shall use the "getBox" function: https://developer.myscript.com/refguides/interactive-ink/android/1.3/com/myscript/iink/ContentBlock.html#getBox--

Please note the latter will return with coordinates in mimiliters rather than in pixels. In order to have pixels, you shall use the "transform": https://developer.myscript.com/refguides/interactive-ink/android/1.3/com/myscript/iink/graphics/Transform.html

Best regards,

Olivier
